name: DCCore
author: Jacksonnn
version: BETA 1.0
main: com.Jacksonnn.DCCore.DCCore
loadbefore: [Essentials, Playtimes]
api-version: 1.13
commands:
  dccore:
    aliases: [dc,dcc,dcore]
    usage: /<command>
  broadcast:
    aliases: [bc, bcast, announce]
    usage: /<command>
  bannedwords:
    aliases: [bw, bwords, bannedw]
    usage: /<command>
  bendingtournament:
    aliases: [bt, tournament, tourney, bendingt, btournament, btourny]
    usage: /<command>
  rankup:
    aliases: [ru, rank, rup]
    usage: /<command>
  playtime:
    usage: /<command>
  ranks:
    usage: /<command>
  diamondluck:
    aliases: [diamondl, dluck, dl]
    usage: /<command>
  randomtp:
    aliases: [randtp, randomteleport, rtp, randteleport]
    usage: /<command>
  dcevents:
    aliases: [events, dce, darkcrestevents, darkcreste]
    usage: /<command>
  b:
    aliases: [pk, projectkorra, bend, bending, atla, alok, tla, lok]
    usage: /<command>
  donate:
    usage: /<command>
  vote:
    usage: /<command>
  forums:
    aliases: [forum, board]
    usage: /<command>
  website:
    aliases: [site, web, www]
    usage: /<command>
  bendinghelp:
    aliases: [bhelp, bendingh, bh]
    usage: /<command>
permissions:
  DCCore.player:
    default: op
    children:
      DCCore.spawner.place: true
      DCCore.spawner.break: true
      DCCore.QuickDeposit.use: true
      bending.tournament.player: true
  DCCore.staff:
    default: op
    children:
      DCCore.GMSpectator: true
      DCCore.broadcast: true
      DCCore.chat: true
      DCCore.AntiCurse.bypass: true
      bending.tournament.admin: true
  DCCore.chat:
    default: op
    children:
      DCCore.chat.toggle: true
      DCCore.chat.staff: true
      DCCore.AntiCurse.bypass: true
  DCCore.EventHost:
    default: op
    children:
      DCCore.broadcast: true
      DCCore.diamondluck: true
      DCCore.bendingtournament: true
      DCCore.EventHost.add: true
      DCCore.EventHost.terminate: true
      DCCore.EventHost.broadcast: true
      DCCore.EventHost.eventList: true
      DCCore.EventHost.playerList: true
      DCCore.EventHost.remove: true
      DCCore.EventHost.create: true
      DCCore.EventHost.teleport: true