name: DCCore
author: Jacksonnn
version: BETA 1.0
main: com.Jacksonnn.DCCore.DCCore
loadbefore: [Essentials]
api-version: 1.13
commands:
  dccore:
    aliases: [dc,dcc,dcore]
    usage: /<command>
  broadcast:
    aliases: [bc, bcast]
    usage: /<command>
  bannedwords:
    aliases: [bw, bwords, bannedw]
    usage: /<command>
  bendingtournament:
    aliases: [bt, tournament, tourney, bendingt, btournament, btourny]
    usage: /<command>
  rankup:
    aliases: [ru, rank, rup]
    usage: /<command>
  playtime:
    usage: /<command>
  ranks:
    usage: /<command>
  diamondluck:
    aliases: [diamondl, dluck, dl]
    usage: /<command>
permissions:
  DCCore.player:
    default: op
    children:
      DCCore.spawner.place: true
      DCCore.spawner.break: true
      DCCore.QuickDeposit.use: true
      bending.tournament.player: true
  DCCore.staff:
    default: op
    children:
      DCCore.GMSpectator: true
      DCCore.broadcast: true
      DCCore.chat: true
      DCCore.AntiCurse.bypass: true
      bending.tournament.admin: true
  DCCore.chat:
    default: op
    children:
      DCCore.chat.toggle: true
      DCCore.chat.staff: true
      DCCore.AntiCurse.bypass: true