name: DCCore
author: Jacksonnn
version: BETA 1.0
main: com.Jacksonnn.DCCore.DCCore
loadbefore: [Essentials]
commands:
  dccore:
    aliases: [dc,dcc,dcore]
    usage: /<command>
  broadcast:
    aliases: [bc, bcast]
    usage: /<command>
permissions:
  DCCore.player:
    default: op
    children:
      DCCore.spawner.place: true
      DCCore.spawner.break: true
      DCCore.quickdeposit.use: true
  DCCore.staff:
    default: op
    children:
      DCCore.GMSpectator: true
      DCCore.broadcast: true
      DCCore.chat: true
      DCCore.AntiCurse.bypass: true
  DCCore.chat:
    default: op
    children:
      DCCore.chat.toggle: true
      DCCore.chat.staff: true
      DCCore.AntiCurse.bypass: true