name: DCCore
author: Jacksonnn
version: BETA v1.0
main: com.Jacksonnn.DCCore.DCCore
loadbefore: [Essentials]
permissions:
  DCCore.spawner.place:
    default: op
  DCCore.spawner.break:
    default: op
  DCCore.quickdeposit.use:
    default: op